version: "3.8"

services:
  convertnest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convertnest_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY:-MY_GEMINI_API_KEY}
    restart: always
